import { candidateBenefits } from '../../lib/recruitingContent';
import { Link } from 'react-router-dom';
import { ArrowUpRight } from 'lucide-react';
import { Benefits } from '../../components/marketing/RecruitingContent';

export default function CandidatesPage() {
  return <div className="firm-page"><section className="firm-inner-hero"><div className="mkt-container"><p className="firm-eyebrow">For candidates</p><h1>Your Next Opportunity Should Fit More Than Your Resume</h1><p className="firm-lead">We help professionals explore opportunities that align with their experience, goals, compensation expectations, and career direction.</p><div className="recruiting-actions"><Link to="/jobs" className="firm-button">View Open Jobs <ArrowUpRight size={18} aria-hidden="true" /></Link><a href="mailto:hello@aliviosearchpartners.com?subject=Career%20conversation%20and%20resume" className="firm-text-link">Submit Your Resume by Email <ArrowUpRight size={18} aria-hidden="true" /></a></div></div></section>
    <section className="firm-section"><div className="mkt-container recruiting-two-col"><div><p className="firm-eyebrow">A personal approach</p><h2>A recruiting partner who respects your time.</h2><p>Share what matters to you in your next role. We take the time to understand your experience and goals, discuss relevant opportunities, and help you prepare for interviews and offers.</p><Benefits items={candidateBenefits} /></div><img className="recruiting-page-image" src="/images/technology-team.jpg" alt="Colleagues enjoying a collaborative conversation" width="850" height="560" /></div></section>
    <section className="firm-section recruiting-about"><div className="mkt-container recruiting-two-col"><div><p className="firm-eyebrow">Your next step</p><h2>Let’s start with a conversation.</h2></div><div><p>Browse our current opportunities and apply directly to a role. If you don’t see the right fit, email your resume and tell us what you are looking for.</p><p>Use your email application to attach your resume before sending it to <a className="firm-text-link" href="mailto:hello@aliviosearchpartners.com">hello@aliviosearchpartners.com</a>.</p><Link to="/jobs" className="firm-button">View Open Jobs <ArrowUpRight size={18} aria-hidden="true" /></Link></div></div></section></div>;
}
