import { Link, useLocation } from 'react-router-dom';
import { useSeo } from '../../lib/seo';

const SITE_URL = 'https://aliviosearchpartners.com';
const CTA_URL = 'https://cal.com/alivio/intro-call30';

type Page = { title: string; description: string; h1: string; eyebrow: string; category: string; sections: { title: string; body: string[] }[]; bullets?: string[] };

const make = (path: string, title: string, h1: string, category: string, sections: string[], bullets: string[] = []): [string, Page] => [path, {
  title: `${title} | Alivio Search Partners`,
  description: `${h1}. Alivio Search Partners combines senior recruiting expertise with AI-enabled sourcing, vetting, and candidate pipeline delivery.`,
  h1,
  eyebrow: category,
  category,
  bullets,
  sections: sections.map((s, i) => ({ title: ['Market context', 'How Alivio supports the search', 'Roles and use cases', 'Execution plan', 'What strong delivery looks like'][i] || 'Next steps', body: [s, 'Alivio approaches every search with a practical blend of human recruiter judgment and AI-enabled workflow support. That means better market mapping, more structured candidate evaluation, stronger outreach, and clearer client-ready reporting without treating hiring as a fully automated transaction.', 'The goal is simple: help hiring teams move from vague demand to qualified conversations faster while preserving candidate quality, compliance awareness, and a strong candidate experience.'] }))
}];

const pages = Object.fromEntries([
make('/services/retained-search','Retained Search','Retained Search for Healthcare and Technology Leadership','Service',['Retained search is built for critical roles where a casual contingency effort is not enough. For healthcare operators, this can mean Director of Nursing, LNHA, clinical leadership, revenue cycle, or physician searches. For technology teams, it can mean engineering leaders, AI product leaders, full-stack engineers, and technical operators who are difficult to find through job posts alone.','Alivio starts by defining the role, the market, the compensation reality, and the candidate profile. From there, we build a targeted search strategy, identify passive candidates, manage outreach, screen for fit, and deliver curated shortlists with clear notes and recommended next steps.','This model is best when the role is urgent, visible, confidential, or difficult to fill. It gives clients a dedicated recruiting partner, a structured process, and a deeper market map than a transactional search.'],['Executive and leadership searches','Confidential hiring projects','Hard-to-fill healthcare and technology roles']),
make('/services/recruitment-as-a-service','Recruitment as a Service','Recruitment as a Service for Recurring Hiring Demand','Service',['Recruitment as a Service is designed for organizations with ongoing hiring demand that need more structure than one-off search support. It is especially useful for healthcare groups, skilled nursing operators, healthtech companies, and growth-stage technology teams that need a repeatable candidate pipeline.','Alivio can support sourcing, screening, outreach workflows, candidate evaluation, submission notes, and weekly pipeline visibility. The service gives clients recruiting capacity without forcing them to build the entire infrastructure internally.','The strongest use cases include multi-role hiring, recurring clinical roles, technical hiring sprints, and organizations that want a consistent market presence with better reporting.'],['Recurring roles','Monthly pipeline support','AI-enabled sourcing workflows']),
make('/industries/healthcare','Healthcare Recruiting','Healthcare Recruiting for Clinical, Operational, and Leadership Roles','Industry',['Healthcare hiring is often constrained by local supply, licensing requirements, shift realities, compensation pressure, and candidate burnout. Generic recruiting methods rarely produce enough qualified conversations for leadership and hard-to-fill clinical roles.','Alivio supports hospitals, skilled nursing groups, post-acute operators, healthcare practices, and healthtech organizations by combining targeted sourcing with structured candidate evaluation. We focus on fit, motivation, compensation alignment, and speed to shortlist.','Common searches include Director of Nursing, LNHA, MDS Coordinator, physicians, allied health, revenue cycle, and healthcare operations leadership.'],['DON, LNHA, MDS, allied health, physicians','Hospitals, SNFs, post-acute, healthcare groups','Structured candidate shortlists']),
make('/industries/technology','Technology Recruiting','Technology Recruiting for AI, Product, Engineering, and GTM Teams','Industry',['Technology hiring requires precision. Strong candidates are often passive, already employed, and evaluating multiple opportunities. Companies need outreach that is relevant, technical enough to earn attention, and aligned with business outcomes.','Alivio helps technology and healthtech teams source and evaluate full-stack engineers, AI and ML talent, technical product managers, data leaders, software architects, and GTM leaders.','Our process emphasizes role calibration, market mapping, candidate motivation, technical fit, and timely follow-up so hiring teams can move quickly without lowering the bar.'],['AI/ML, full-stack, product, data, GTM','Healthtech and software companies','Passive candidate sourcing']),
make('/nearshore-latam-recruiting','Nearshore LATAM Recruiting','Nearshore LATAM Recruiting for U.S. Healthcare and Technology Teams','Nearshore',['Nearshore LATAM recruiting helps U.S. companies access skilled talent in aligned time zones. For technology teams, LATAM can support engineering, product, data, design, operations, and GTM roles. For healthcare-adjacent companies, nearshore talent can strengthen administrative, revenue cycle, customer success, and technical support functions.','Alivio helps define the role, target markets, compensation bands, language requirements, time-zone overlap, and evaluation process. The objective is not simply to find lower-cost talent, but to identify capable professionals who can integrate into U.S. teams.','Strong nearshore hiring requires clear communication standards, structured interviews, realistic compensation, and a thoughtful onboarding process.'],['LATAM talent strategy','Time-zone aligned hiring','Technical and operational roles']),
make('/nearshore-latam-talent','Nearshore LATAM Talent','Nearshore LATAM Talent for Growing U.S. Teams','Nearshore',['LATAM talent can be a strong option for U.S. companies that need specialized skills, strong English communication, and real-time collaboration. The opportunity is especially relevant for product, engineering, customer success, operations, and recruiting support roles.','Alivio supports the full funnel: role definition, sourcing, outreach, screening, candidate comparison, and shortlist delivery. We help clients avoid the common mistakes of under-scoping the role or relying only on job-board applicants.','The best outcomes happen when hiring teams treat nearshore candidates as core team members with clear expectations, good onboarding, and competitive market-aligned offers.'],['Sourcing across LATAM','English and time-zone fit','Structured shortlist delivery']),
make('/recruiting-agency-nyc','Recruiting Agency NYC','Recruiting Agency in NYC for Healthcare and Technology Hiring','Location',['New York City is one of the most competitive talent markets in the country. Healthcare employers, healthtech firms, software companies, and founder-led teams compete for candidates who have options and limited time.','Alivio supports NYC searches with targeted sourcing, AI-enabled research, structured outreach, and senior recruiter judgment. We help clients clarify the role, understand the market, and reach candidates who are not actively applying.','Common NYC searches include physicians, clinical leaders, revenue cycle operators, AI product managers, full-stack engineers, and GTM leaders.'],['NYC healthcare and tech recruiting','Passive candidate sourcing','Executive and specialized searches']),
make('/recruiting-agency-westchester','Recruiting Agency Westchester','Recruiting Agency in Westchester for Healthcare and Technology Teams','Location',['Westchester employers need recruiting support that understands both the New York metro market and local hiring dynamics. Healthcare groups, skilled nursing operators, practices, and technology teams often compete with NYC employers for the same candidate pool.','Alivio helps Westchester organizations build targeted candidate pipelines for clinical, administrative, operational, and technical roles. We focus on quality conversations, clear screening notes, and fast shortlist delivery.','The strongest searches begin with a realistic candidate profile, compensation alignment, and outreach that explains why the opportunity is worth a candidate’s attention.'],['Westchester recruiting support','Healthcare and tech roles','Local and regional search strategy']),
make('/recruiting-agency-yonkers','Recruiting Agency Yonkers','Recruiting Agency in Yonkers for Healthcare and Technology Hiring','Location',['Yonkers sits inside a dense and competitive regional labor market. Employers can access talent across Westchester, NYC, Connecticut, and New Jersey, but outreach must be precise to cut through candidate noise.','Alivio supports Yonkers-area hiring for healthcare leadership, clinical, operational, and technical roles. Our process combines market mapping, candidate outreach, evaluation, and client-ready submissions.','For hard-to-fill searches, speed matters, but so does fit. Alivio helps clients avoid wasting interview time by presenting candidates with clear context and rationale.'],['Yonkers recruiting agency','Healthcare leadership search','Technology and operational hiring']),
make('/recruiting-agency-medellin','Recruiting Agency Medellin','Recruiting Agency in Medellín for Nearshore and Bilingual Talent','Location',['Medellín has become an important talent market for companies seeking bilingual, nearshore professionals with strong collaboration potential. U.S. teams increasingly look to Colombia for technical, operational, customer success, recruiting, and administrative roles.','Alivio helps clients evaluate Medellín talent through a U.S.-focused lens: communication, role fit, time-zone overlap, compensation expectations, and long-term retention potential.','The best Medellín searches are structured, respectful of local market dynamics, and clear about expectations from the start.'],['Medellín nearshore recruiting','Bilingual talent','U.S.-aligned hiring support']),
make('/locations/sao-paulo','São Paulo Recruiting','São Paulo Recruiting for Nearshore Technology and Business Talent','Location',['São Paulo is one of Latin America’s largest business and technology markets. For U.S. companies, it can be a strong source of engineering, product, operations, customer success, finance, and GTM talent.','Alivio helps teams approach São Paulo recruiting with clear role requirements, realistic compensation expectations, and structured evaluation. We support sourcing and screening workflows that help clients compare candidates consistently.','Nearshore recruiting works best when companies commit to strong communication norms, documented expectations, and a hiring process that respects candidate time.'],['Brazil talent market','Technology and business roles','Nearshore recruiting process']),
make('/locations/buenos-aires','Buenos Aires Recruiting','Buenos Aires Recruiting for Nearshore Technology and Operations Talent','Location',['Buenos Aires has a deep professional talent pool across software, product, design, operations, finance, and customer-facing roles. U.S. companies often value the time-zone alignment and experience many candidates have with international teams.','Alivio supports searches by defining the target profile, building sourcing lists, engaging passive candidates, and evaluating fit through a structured process.','For clients, the priority is not simply volume. It is finding candidates who can communicate clearly, operate independently, and integrate with U.S. teams.'],['Argentina talent market','Nearshore operations and tech','Structured evaluation']),
make('/platform','Alivio Platform','Alivio Platform for AI-Enabled Recruiting Execution','Platform',['The Alivio platform concept brings structure to recruiting execution: role definition, candidate sourcing, screening support, outreach workflows, pipeline visibility, and client-ready shortlist delivery.','AI is used to support research, matching, summarization, outreach drafting, and workflow organization. Human recruiters remain responsible for judgment, calibration, candidate communication, and final recommendations.','The platform is designed for healthcare and technology teams that want faster execution without losing the human quality control required for hiring decisions.'],['AI-enabled search workflow','Human-in-the-loop recruiting','Pipeline visibility']),
make('/why-alivio','Why Alivio','Why Alivio Search Partners for Healthcare and Technology Recruiting','Company',['Alivio is built for organizations that need more than resume forwarding. We focus on role calibration, targeted sourcing, structured evaluation, and clear communication throughout the search.','The difference is the operating model: senior recruiting judgment supported by AI-enabled workflows. This creates better search discipline, faster research, and more consistent candidate presentation.','Clients choose Alivio when they need speed, precision, and a partner who understands the realities of hard-to-fill healthcare and technical roles.'],['Senior recruiter-led','AI-enabled workflows','Healthcare and technology specialization']),
make('/results','Recruiting Results','Recruiting Results, Pipeline Visibility, and Search Outcomes','Company',['Strong recruiting results come from a disciplined process, not random activity. Alivio measures progress through market coverage, candidate engagement, screen quality, shortlist readiness, interview conversion, and follow-up discipline.','We help clients understand what is happening inside a search: where candidates are responding, where compensation may be misaligned, and what adjustments can improve outcomes.','The objective is to create a hiring pipeline that is visible, actionable, and connected to real candidate conversations.'],['Pipeline reporting','Shortlist quality','Search process visibility']),
make('/accelerator','Hiring Accelerator','Hiring Accelerator for Critical Healthcare and Technology Roles','Offer',['The Alivio Hiring Accelerator is designed for companies that need to move quickly on urgent or high-priority roles. It creates a focused sprint around role calibration, target market mapping, outreach, screening, and shortlist delivery.','This approach is useful when a role has been open too long, internal bandwidth is constrained, or the hiring team needs a sharper market view before committing to a longer search.','The accelerator works best when the client is ready to provide fast feedback, clear requirements, and interview availability.'],['Hiring sprint','Critical roles','Faster shortlist creation']),
make('/ai-transparency','AI Transparency','AI Transparency in Recruiting at Alivio Search Partners','Company',['Alivio uses AI to support recruiting workflows, not to replace human hiring judgment. AI can assist with sourcing research, profile summarization, outreach drafting, fit-score organization, and pipeline prioritization.','Human review remains central. Recruiters evaluate context, candidate motivation, communication quality, compensation alignment, and client-specific requirements before making recommendations.','Responsible use of AI in recruiting requires attention to privacy, fairness, accuracy, and accountability. Alivio treats AI as a productivity layer, not a final decision-maker.'],['Human review','Responsible AI use','Privacy and fairness awareness']),
make('/careers','Careers at Alivio','Careers at Alivio Search Partners','Company',['Alivio is building a modern recruiting firm for healthcare and technology hiring. We are interested in people who care about candidate experience, client outcomes, disciplined execution, and practical use of AI.','Strong team members are curious, organized, direct, and comfortable operating in a fast-moving environment. Recruiting experience is valuable, but so is a strong work ethic and ability to learn quickly.','Candidates interested in future opportunities with Alivio can reach out and share their background.'],['Recruiting careers','AI-enabled search','Healthcare and tech focus']),
make('/apply','Apply with Alivio','Apply for Opportunities Through Alivio Search Partners','Candidate',['Alivio works with candidates across healthcare, technology, operations, product, and leadership roles. If your background aligns with one of our active or future searches, we want to understand your goals, experience, and ideal next step.','A strong candidate profile includes role history, measurable outcomes, compensation expectations, location or remote preferences, licensing or technical skills, and timing.','Our goal is to represent candidates accurately and respectfully while matching them with roles where they can succeed.'],['Candidate intake','Healthcare and tech roles','Confidential career conversations']),
make('/start','Start a Search','Start a Recruiting Search with Alivio','Conversion',['Starting a search begins with clarity. Alivio needs to understand the role, why it is open, what success looks like, compensation, urgency, must-have requirements, and the hiring process.','Once the search is defined, we can build a target market, begin outreach, screen candidates, and deliver structured shortlists.','The faster clients provide feedback, the faster the search improves. A strong partnership creates better calibration and stronger candidate conversion.'],['Role intake','Search calibration','Book an intro call']),
make('/schedule','Schedule a Call','Schedule an Intro Call with Alivio Search Partners','Conversion',['Use this page to schedule a short introductory call with Alivio Search Partners. The purpose is to understand what you are hiring for, what has been difficult so far, and whether Alivio is a fit.','A productive call usually covers the role, location or remote expectations, compensation range, timing, candidate profile, and current recruiting process.','After the call, Alivio can recommend a practical search strategy and next steps.'],['20–30 minute intro call','Hiring strategy discussion','Clear next steps']),
make('/roi-calculator','Recruiting ROI Calculator','Recruiting ROI Calculator for Hiring Teams','Tool',['Recruiting ROI is driven by time-to-fill, vacancy cost, agency spend, internal recruiter bandwidth, overtime or premium labor costs, and the quality of candidates presented.','For healthcare organizations, delayed hiring can increase premium labor, manager workload, and burnout. For technology companies, delayed hiring can slow product delivery, customer commitments, and revenue execution.','Use this page as a framework: estimate daily vacancy cost, multiply by days saved, subtract search investment, and compare the operational impact of faster qualified hiring.'],['Vacancy cost','Time-to-fill savings','Pipeline quality']),
make('/privacy-policy','Privacy Policy','Privacy Policy for Alivio Search Partners','Legal',['Alivio Search Partners may collect business contact information, candidate information, resumes, communication history, scheduling details, and information submitted through forms or recruiting conversations.','We use this information to provide recruiting services, evaluate candidate fit, communicate with clients and candidates, operate the website, improve workflows, and meet legal or operational obligations.','We do not present AI-generated recommendations as final hiring decisions. Candidate and client information should be handled with care, access controls, and appropriate confidentiality.'],['Information collected','How information is used','Recruiting data practices']),
make('/terms-of-service','Terms of Service','Terms of Service for Alivio Search Partners','Legal',['These terms describe the general conditions for using the Alivio Search Partners website and engaging with our recruiting services. Website content is provided for informational purposes and does not create a binding search agreement by itself.','Specific recruiting engagements may be governed by separate written agreements, including fee terms, replacement provisions, confidentiality, scope of work, and client responsibilities.','Users should not misuse the site, submit false information, attempt unauthorized access, or rely on website content as legal, financial, or employment advice.'],['Website use','Recruiting engagement terms','Limitations and responsibilities']),
make('/accessibility','Accessibility Statement','Accessibility Statement for Alivio Search Partners','Legal',['Alivio Search Partners aims to provide a website experience that is usable for visitors across devices and accessibility needs. We work to support clear navigation, readable content, semantic structure, and sufficient contrast.','Accessibility is an ongoing process. As the site evolves, we aim to improve keyboard navigation, heading structure, link clarity, form labels, and compatibility with assistive technologies.','Visitors who encounter accessibility barriers can contact Alivio with details so the issue can be reviewed and addressed.'],['Accessible content','Ongoing improvements','Feedback welcome']),
] as [string, Page][]);

const blogTitles: Record<string, string> = {
 'creating-float-pool-strategies-that-lower-premium-labor-costs':'Creating Float Pool Strategies That Lower Premium Labor Costs','ai-talent-partner-guide':'AI Talent Partner Guide','how-chatbots-support-candidate-experience-in-healthcare':'How Chatbots Support Candidate Experience in Healthcare','what-recruiters-need-to-know-about-traveler-preferences':'What Recruiters Need to Know About Traveler Preferences','hiring-software-engineers':'Hiring Software Engineers','emergency-medicine-physician-recruiting':'Emergency Medicine Physician Recruiting','virtual-interviewing-best-practices':'Virtual Interviewing Best Practices','technical-skills-assessment-methods':'Technical Skills Assessment Methods','ai-copilots-recruitment-teams':'AI Copilots for Recruitment Teams','compensation-benchmarking-strategies':'Compensation Benchmarking Strategies','healthcare-leadership-development':'Healthcare Leadership Development','building-tech-teams':'Building Tech Teams','predictive-analytics-hiring-needs':'Predictive Analytics for Hiring Needs','employer-branding-talent-attraction':'Employer Branding and Talent Attraction','healthcare-staffing-crisis':'Healthcare Staffing Crisis','nursing-recruitment-trends':'Nursing Recruitment Trends','facility-design-staff-recruitment':'Facility Design and Staff Recruitment','skills-based-hiring-beyond-degrees':'Skills-Based Hiring Beyond Degrees','onboarding-retention-strategies':'Onboarding and Retention Strategies','pipeline-staff-pool-pilot-guide':'Pipeline Staff Pool Pilot Guide'
};

for (const [slug, title] of Object.entries(blogTitles)) pages[`/blog/${slug}`] = { title: `${title} | Alivio Search Partners Blog`, description: `${title} with practical recruiting guidance for healthcare and technology hiring teams.`, h1: title, eyebrow: 'Recruiting Insight', category: 'Blog', bullets: ['Practical recruiting strategy','AI-enabled workflow perspective','Human-centered candidate experience'], sections: ['Hiring teams need practical guidance that connects strategy to execution. This article explains how leaders can think about the topic, where recruiting teams often lose momentum, and how a more structured process improves outcomes.','For healthcare and technology organizations, the strongest recruiting programs combine market knowledge, clear role definition, strong candidate communication, and disciplined follow-up. AI can support research, summarization, and workflow speed, but human judgment remains essential.','Use this guidance to evaluate your current process, identify gaps, and build a more reliable pipeline of qualified candidates.'].map((s,i)=>({title:['Why this matters','How recruiting teams should respond','Practical next steps'][i], body:[s,s,s]})) };

const jobs = {
 '/jobs/emergency-medicine-physician-new-york-ny':['Emergency Medicine Physician – New York, NY','Emergency Medicine Physician opportunity in New York, NY for physicians who can operate in a fast-paced clinical environment.'],
 '/jobs/product-manager-clinical-systems-chicago-il':['Product Manager, Clinical Systems – Chicago, IL','Product Manager opportunity focused on clinical systems, healthcare workflows, stakeholder alignment, and product execution.'],
 '/jobs/physical-therapist-outpatient-denver-co':['Physical Therapist, Outpatient – Denver, CO','Outpatient Physical Therapist opportunity in Denver for clinicians focused on patient outcomes, documentation quality, and team collaboration.']
};
for (const [path,[h1,intro]] of Object.entries(jobs)) pages[path] = { title: `${h1} | Alivio Search Partners`, description: intro, h1, eyebrow:'Featured Role', category:'Jobs', bullets:['Candidate profile review','Confidential recruiter conversation','Client-ready submission support'], sections: ['This role page is maintained by Alivio Search Partners for candidates exploring relevant opportunities and employers benchmarking similar searches. The exact employer details, compensation, and requirements may vary by search stage and client requirements.','Strong candidates should be prepared to discuss their experience, measurable outcomes, licensing or technical requirements, preferred work environment, compensation expectations, and timing.','Alivio evaluates fit through a structured process and presents qualified candidates with clear notes around motivation, qualifications, availability, and next steps.'].map((s,i)=>({title:['Opportunity overview','Candidate profile','How to apply'][i], body:[i===0?intro:s,s,s]})) };

export { pages as seoRecoveryPages };

export default function SeoRecoveryPage() {
 const location = useLocation();
 const page = pages[location.pathname];
 useSeo({ title: page?.title || 'Alivio Search Partners', description: page?.description || 'AI-enabled recruiting and executive search for healthcare and technology organizations.', canonicalUrl: `${SITE_URL}${location.pathname}`, robots: 'index, follow', structuredData: page ? { '@context':'https://schema.org', '@type':'WebPage', name: page.title, description: page.description, url: `${SITE_URL}${location.pathname}` } : undefined });
 if (!page) return <div className="mkt-container" style={{padding:'70px 0'}}><h1>Page not found</h1><Link to="/">Return home</Link></div>;
 return <main>
  <section style={{background:'linear-gradient(135deg,#061636,#0B2A63)', color:'#fff', padding:'72px 0'}}><div className="mkt-container" style={{maxWidth:980}}><p className="mkt-label" style={{color:'#9DBBFF'}}>{page.eyebrow}</p><h1 style={{fontSize:'clamp(38px,5vw,64px)',lineHeight:1.04,letterSpacing:'-.04em',margin:'14px 0'}}>{page.h1}</h1><p style={{fontSize:20,lineHeight:1.7,color:'rgba(255,255,255,.78)'}}>{page.description}</p><a className="mkt-btn-primary-lg" href={CTA_URL} target="_blank" rel="noreferrer" style={{display:'inline-flex',marginTop:18,background:'#fff',color:'#061636'}}>Book an Intro Call</a></div></section>
  <section className="mkt-container" style={{padding:'48px 0 24px',maxWidth:980}}>{page.bullets?.length ? <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12,marginBottom:30}} className="seo-bullets">{page.bullets.map(b=><div key={b} style={{border:'1px solid #E1E8F3',borderRadius:14,padding:16,fontWeight:700,color:'#263859'}}>{b}</div>)}</div>:null}{page.sections.map(sec=><section key={sec.title} style={{marginBottom:34}}><h2 style={{fontSize:30,letterSpacing:'-.02em',color:'#102344'}}>{sec.title}</h2>{sec.body.map((p,i)=><p key={i} style={{fontSize:17,lineHeight:1.78,color:'#4D5E7B'}}>{p}</p>)}</section>)}<section style={{border:'1px solid #DCE4F2',borderRadius:18,padding:28,background:'#F9FBFF'}}><h2>Talk with Alivio Search Partners</h2><p style={{color:'#4D5E7B',fontSize:17,lineHeight:1.7}}>Whether you are hiring for healthcare leadership, clinical talent, engineering, product, or nearshore support, Alivio can help map the search and build a stronger candidate pipeline.</p><a className="mkt-btn-primary-lg" href={CTA_URL} target="_blank" rel="noreferrer">Book an Intro Call</a></section></section><style>{`@media(max-width:800px){.seo-bullets{grid-template-columns:1fr!important}}`}</style>
 </main>;
}
