// Local PostgreSQL integration test, no network, real applicant data, or email sends.
// ATS_PGLITE_MODULE=/tmp/alivio-ats-sql-test/node_modules/@electric-sql/pglite/dist/index.js node --test tests/server/application-database.test.mjs
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const modulePath = process.env.ATS_PGLITE_MODULE;
const uid = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const payload = n => ({ submission_id: uid(n), job_id: 1, first_name: 'Synthetic', last_name: 'Example', email: 'synthetic@example.test', questionnaire: { location: 'Boston', experience: 'Five years', skills: 'Research', availability: 'Soon', interest: 'Role' } });
test('ATS migration, transactional intake, RLS, mapping, message lifecycle and outbox replay', { skip: !modulePath }, async () => {
  const { PGlite } = await import(modulePath); const db = new PGlite();
  try {
    await db.exec(`
      create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create schema storage;
      create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      create function auth.role() returns text language sql as $$select current_setting('request.jwt.claim.role',true)$$;
      create table auth.users(id uuid primary key);
      create table public.organizations(id uuid primary key default gen_random_uuid(),name text,size text,industry text);
      create table public.users(id uuid primary key references auth.users,org_id uuid not null references organizations,full_name text not null,email text not null,role text,is_active boolean not null default true);
      create table public.roles(id uuid primary key,org_id uuid not null references organizations,title text,status text default 'active');
      create table public.jobs(id bigint generated always as identity primary key,title text not null);
      create table public.candidates(id uuid primary key default gen_random_uuid(),org_id uuid not null references organizations,role_id uuid not null references roles,full_name text not null,email text,phone text,location text,source text,pipeline_stage text default 'discovered' check(pipeline_stage in ('discovered','scored','voice_qualified','engaged','responded','scheduled','archived')),profile_data jsonb,created_at timestamptz default now(),updated_at timestamptz default now());
      create table public.applications(id bigint generated always as identity primary key,job_id bigint references jobs,first_name text not null,last_name text not null,email text not null,phone text,linkedin_url text,resume_url text,status text default 'pending',created_at timestamptz default now(),user_id uuid);
      create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text); alter table storage.objects enable row level security;
      grant usage on schema public,auth,storage to anon,authenticated,service_role;
      grant select,insert,update,delete on all tables in schema public,storage to authenticated;
      create policy broad_storage_read on storage.objects for select to authenticated using(true);
      alter table public.users enable row level security;
      create policy self_update on public.users for all to authenticated using(auth.uid()=id) with check(auth.uid()=id);
    `);
    await db.exec(await readFile(new URL('../../supabase/migrations/20260909051734_candidate_ats_email_workflow.sql', import.meta.url), 'utf8'));
    await db.exec(`grant all on all tables in schema public,storage to service_role; grant all on all sequences in schema public to service_role;
      insert into auth.users values('${uid(1)}'),('${uid(2)}'),('${uid(3)}'),('${uid(4)}');
      insert into organizations(id) values('${uid(10)}'),('${uid(20)}');
      insert into public.users(id,org_id,full_name,email,role) values('${uid(1)}','${uid(10)}','Admin','admin@example.test','admin'),('${uid(2)}','${uid(20)}','Other','other@example.test','admin'),('${uid(3)}','${uid(10)}','Viewer','viewer@example.test','viewer'),('${uid(4)}','${uid(10)}','Platform','platform@example.test','owner');
      insert into roles values('${uid(11)}','${uid(10)}','Synthetic role','active'),('${uid(21)}','${uid(20)}','Other role','active');
      insert into jobs(title) values('Synthetic public job'),('Triage job');
      insert into application_platform_admins values('${uid(4)}');
      insert into storage.objects(bucket_id,name) values('application-resumes','secret.pdf'),('other','okay');
      set request.jwt.claim.role='service_role'; set role service_role;
    `);
    const rpc = async (fn, args) => (await db.query(`select public.${fn}(${args.map((_, i) => '$' + (i + 1)).join(',')}) as result`, args)).rows[0].result;
    const recruiter = (actor, action) => rpc('ats_recruiter', [uid(actor), JSON.stringify(action), false]);
    assert.equal(await rpc('ats_rate_limit', ['test-rate', 2, 3600]), true);
    assert.equal(await rpc('ats_rate_limit', ['test-rate', 2, 3600]), true);
    assert.equal(await rpc('ats_rate_limit', ['test-rate', 2, 3600]), false, 'rate limit persists across database calls');
    await recruiter(4, { action: 'map-job', job_id: 1, role_id: uid(11) });
    await db.query('insert into application_uploads(path) values($1)', ['first.pdf']);
    const ref = await rpc('ats_submit', [JSON.stringify(payload(100)), 'hash-one', 'first.pdf', 'resume.pdf']);
    assert.match(ref, /^ASP-/);
    const again = await rpc('ats_submit', [JSON.stringify(payload(100)), 'hash-one', 'not-needed.pdf', 'resume.pdf']);
    assert.equal(again, ref);
    await assert.rejects(rpc('ats_submit', [JSON.stringify(payload(100)), 'different-hash', 'first.pdf', 'resume.pdf']), /submission_conflict/);
    let rows = (await db.query('select * from applications')).rows;
    assert.equal(rows.length, 1); assert.equal(rows[0].org_id, uid(10)); assert.ok(rows[0].candidate_id);
    const id = rows[0].id;
    await db.exec('update jobs set accepting_applications=false where id=1');
    await assert.rejects(rpc('ats_submit', [JSON.stringify(payload(199)), 'closed-hash', 'first.pdf', 'resume.pdf']), /job_unavailable/);
    await db.exec('update jobs set accepting_applications=true where id=1');
    await assert.rejects(rpc('ats_submit', [JSON.stringify(payload(199)), 'no-file-hash', 'unknown.pdf', 'resume.pdf']), /invalid_upload/);
    assert.equal((await db.query('select * from applications')).rows.length,1,'failed transaction leaves no partial application');
    assert.equal((await db.query('select * from application_outbox')).rows.length, 2);
    assert.equal((await recruiter(1, { action: 'list' })).applications.length, 1);
    assert.equal((await recruiter(2, { action: 'list' })).applications.length, 0);
    await assert.rejects(recruiter(2, { action: 'detail', id }), /forbidden/);
    await assert.rejects(recruiter(3, { action: 'update', id, status: 'screening' }), /forbidden/);
    await assert.rejects(recruiter(3, { action: 'detail', id }), /forbidden/);
    await assert.rejects(recruiter(3, { action: 'resume', id }), /forbidden/);
    await assert.rejects(recruiter(1, { action: 'update', id, status: null }), /invalid_status/);
    await recruiter(1, { action: 'update', id, status: 'interview', assigned_to: uid(1), note: 'Synthetic note', next_action: 'Schedule' });
    assert.equal((await db.query('select pipeline_stage from candidates')).rows[0].pipeline_stage, 'scheduled');
    await assert.rejects(recruiter(1, { action: 'message', request_id: uid(502), id, subject: 'Follow-up', body: 'Test', scheduled_at: new Date(Date.now() + 60000).toISOString() }), /followups_unavailable/);
    await db.query('insert into application_uploads(path) values($1)', ['second.pdf']);
    await rpc('ats_submit', [JSON.stringify(payload(101)), 'hash-two', 'second.pdf', 'resume.pdf']);
    assert.equal((await db.query('select * from candidates')).rows.length, 1, 'same role/email links same candidate');
    await db.query('insert into application_uploads(path) values($1)', ['triage.pdf']);
    await rpc('ats_submit', [JSON.stringify({ ...payload(102), job_id: 2 }), 'hash-three', 'triage.pdf', 'resume.pdf']);
    assert.equal((await recruiter(1, { action: 'list' })).applications.length, 2, 'unmapped triage hidden from ordinary org admin');
    await recruiter(4, { action: 'map-job', job_id: 2, role_id: uid(21) });
    assert.equal((await recruiter(2, { action: 'list' })).applications.length, 1);
    await assert.rejects(recruiter(4, { action: 'map-job', job_id: 2, role_id: uid(11) }), /job_already_mapped/);
    // A committed schedule can be retried after due time and after worker retry timing changes.
    const scheduledRequest = { action: 'message', request_id: uid(550), id, subject: 'Scheduled retry test', body: 'Synthetic follow-up', scheduled_at: new Date(Date.now()+1000).toISOString() };
    await rpc('ats_recruiter', [uid(1), JSON.stringify(scheduledRequest), true]);
    await new Promise(resolve => setTimeout(resolve, 1100));
    assert.deepEqual(await rpc('ats_recruiter', [uid(1), JSON.stringify(scheduledRequest), true]), { ok: true }, 'committed request remains retryable after its due time');
    await assert.rejects(rpc('ats_recruiter', [uid(1), JSON.stringify({ ...scheduledRequest, request_id: uid(551) }), true]), /invalid_schedule/, 'new requests cannot schedule in the past');
    const scheduledMessage = (await db.query('select * from application_outbox where event_key=$1', [`manual:${id}:${uid(550)}`])).rows[0];
    await db.query("update application_outbox set status='sending', attempts=1,first_attempt_at=now(),lease_token=$1,lease_until=now()+interval '5 minutes' where id=$2", [uid(552), scheduledMessage.id]);
    await rpc('ats_finish_message', [scheduledMessage.id, uid(552), null, 'provider_http_429', 3600]);
    const retriedSchedule = (await db.query('select scheduled_at,next_attempt_at from application_outbox where id=$1', [scheduledMessage.id])).rows[0];
    assert.equal(new Date(retriedSchedule.scheduled_at).toISOString(), scheduledRequest.scheduled_at, 'original schedule is immutable');
    assert.ok(new Date(retriedSchedule.next_attempt_at)>new Date(retriedSchedule.scheduled_at), 'worker tracks retry timing separately');
    assert.deepEqual(await rpc('ats_recruiter', [uid(1), JSON.stringify(scheduledRequest), true]), { ok: true }, 'worker retry does not invalidate request idempotency');
    assert.equal((await db.query('select * from application_outbox where event_key=$1', [`manual:${id}:${uid(550)}`])).rows.length,1);
    await db.query("update application_outbox set status='cancelled' where id=$1", [scheduledMessage.id]);
    // Provider failure leaves application intact and no false sent_at.
    let claimed = (await db.query('select * from ats_claim_messages(false)')).rows;
    const message = claimed[0];
    const original = await rpc('ats_prepare_message', [message.id, message.lease_token, 'Alivio <mail@example.test>', 'internal@example.test', 'reply.example.test', false]);
    const frozen = await rpc('ats_prepare_message', [message.id, message.lease_token, 'changed@example.test', 'changed@example.test', '', false]);
    assert.deepEqual(original, frozen);
    await rpc('ats_finish_message', [message.id, message.lease_token, null, 'provider_http_429', 0]);
    assert.equal((await db.query('select sent_at from application_outbox where id=$1', [message.id])).rows[0].sent_at, null);
    claimed = (await db.query('select * from ats_claim_messages(false)')).rows;
    assert.equal(claimed.length, 1, 'leased work is not claimed twice');
    // Early delivery event is reconciled when accepted response arrives.
    await rpc('ats_webhook', ['early-event', JSON.stringify({ type: 'email.delivered', data: { email_id: 'provider-test' } }), 'reply.example.test']);
    await rpc('ats_finish_message', [message.id, claimed[0].lease_token, 'provider-test', null, null]);
    assert.equal((await db.query('select status from application_outbox where id=$1', [message.id])).rows[0].status, 'delivered');
    await recruiter(1, { action: 'update', id, status: 'rejected' });
    await recruiter(1, { action: 'message', request_id: uid(500), id, subject: 'Status update', body: 'Synthetic rejection message' });
    await recruiter(1, { action: 'message', request_id: uid(500), id, subject: 'Status update', body: 'Synthetic rejection message' });
    assert.equal((await db.query("select * from application_outbox where kind='manual'")).rows.length,1,'manual retry does not duplicate email');
    await assert.rejects(recruiter(1, { action: 'message', request_id: uid(500), id, subject: 'Changed', body: 'Different content' }), /message_conflict/);
    const token = (await db.query('select reply_token from applications where id=$1', [id])).rows[0].reply_token;
    const reply = JSON.stringify({ type: 'email.received', data: { email_id: 'received-1', to: [`applications+${token}@reply.example.test`] } });
    await rpc('ats_webhook', ['reply-event', reply, 'reply.example.test']);
    await rpc('ats_webhook', ['reply-event', reply, 'reply.example.test']);
    assert.equal((await db.query("select * from application_events where event_type='reply_received'")).rows.length, 1);
    await recruiter(1, { action: 'message', request_id: uid(501), id, subject: 'Response', body: 'Deliberate manual recruiter response' });
    await assert.rejects(rpc('ats_recruiter', [uid(1), JSON.stringify({ action: 'message', request_id: uid(502), id, subject: 'Follow-up', body: 'Must stop', scheduled_at: new Date(Date.now()+60000).toISOString() }), true]), /followups_unavailable/);
    await recruiter(1, { action: 'stop-messages', id });
    await assert.rejects(recruiter(1, { action: 'message', request_id: uid(503), id, subject: 'More', body: 'Stopped' }), /messages_stopped/);
    await db.exec("update application_outbox set status='sending',attempts=6,lease_until=now()-interval '1 minute' where status='sending'");
    await db.query('select * from ats_claim_messages(false)');
    assert.equal((await db.query("select * from application_outbox where status='sending' and attempts>=6")).rows.length,0,'crashed final attempt becomes terminal failure');
    await db.exec(`reset role; set request.jwt.claim.role='authenticated'; set request.jwt.claim.sub='${uid(2)}'; set role authenticated;`);
    assert.equal((await db.query('select * from applications')).rows.length, 1, 'RLS only own org');
    assert.equal((await db.query('select * from storage.objects')).rows.length, 1, 'private bucket overrides permissive storage policy');
    await assert.rejects(db.query("update public.users set org_id=$1 where id=$2", [uid(10), uid(2)]), /Membership changes/);
    await assert.rejects(db.query("update public.users set role='owner' where id=$1", [uid(2)]), /Membership changes/);
    await assert.rejects(recruiter(4, { action: 'list' }), /permission denied/, 'authenticated callers cannot forge RPC actor');
    await assert.rejects(rpc('create_organization_and_user', ['Forged org','1-50','Test',uid(1),'Forged','x@example.test']), /User mismatch/);
    assert.equal(await rpc('create_organization_and_user', ['New org','1-50','Test',uid(2),'Existing','x@example.test']),uid(20), 'existing onboarding cannot rehome user');
    await db.exec("reset role; set request.jwt.claim.role='anon'; set role anon;");
    await assert.rejects(db.query('select * from applications'), /permission denied/);
    await assert.rejects(db.query('select * from application_outbox'), /permission denied/);
  } finally { await db.close(); }
});
