import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const modulePath=process.env.ATS_PGLITE_MODULE;
const uid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
test('interview migration, access boundaries, approval idempotency, consent and server deadline', {skip:!modulePath}, async()=>{
 const {PGlite}=await import(modulePath);const db=new PGlite();
 try {
    await db.exec(`
      create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create schema storage;
      create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      create function auth.role() returns text language sql as $$select current_setting('request.jwt.claim.role',true)$$;
      create table auth.users(id uuid primary key);
      create table public.organizations(id uuid primary key default gen_random_uuid(),name text,size text,industry text);
      create table public.users(id uuid primary key references auth.users,org_id uuid not null references organizations,full_name text not null,email text not null,role text,is_active boolean not null default true);
      create table public.roles(id uuid primary key,org_id uuid not null references organizations,title text,status text default 'active');
      create table public.jobs(id bigint generated always as identity primary key,title text not null);
      create table public.candidates(id uuid primary key default gen_random_uuid(),org_id uuid not null references organizations,role_id uuid not null references roles,full_name text not null,email text,phone text,location text,source text,pipeline_stage text default 'discovered' check(pipeline_stage in ('discovered','scored','voice_qualified','engaged','responded','scheduled','archived')),profile_data jsonb,created_at timestamptz default now(),updated_at timestamptz default now());
      create table public.applications(id bigint generated always as identity primary key,job_id bigint references jobs,first_name text not null,last_name text not null,email text not null,phone text,linkedin_url text,resume_url text,status text default 'pending',created_at timestamptz default now(),user_id uuid);
      create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text); alter table storage.objects enable row level security;
      grant usage on schema public,auth,storage to anon,authenticated,service_role;
      grant select,insert,update,delete on all tables in schema public,storage to authenticated;
      create policy broad_storage_read on storage.objects for select to authenticated using(true);
      alter table public.users enable row level security;
      create policy self_update on public.users for all to authenticated using(auth.uid()=id) with check(auth.uid()=id);
    `);
    await db.exec(await readFile(new URL('../../supabase/migrations/20260909051734_candidate_ats_email_workflow.sql', import.meta.url), 'utf8'));
    await db.exec(`grant all on all tables in schema public,storage to service_role; grant all on all sequences in schema public to service_role;
      insert into auth.users values('${uid(1)}'),('${uid(2)}'),('${uid(3)}'),('${uid(4)}');
      insert into organizations(id) values('${uid(10)}'),('${uid(20)}');
      insert into public.users(id,org_id,full_name,email,role) values('${uid(1)}','${uid(10)}','Admin','admin@example.test','admin'),('${uid(2)}','${uid(20)}','Other','other@example.test','admin'),('${uid(3)}','${uid(10)}','Viewer','viewer@example.test','viewer'),('${uid(4)}','${uid(10)}','Platform','platform@example.test','owner');
      insert into roles values('${uid(11)}','${uid(10)}','Synthetic role','active'),('${uid(21)}','${uid(20)}','Other role','active');
      insert into jobs(title) values('Synthetic public job'),('Triage job');
      insert into application_platform_admins values('${uid(4)}');
      insert into storage.objects(bucket_id,name) values('application-resumes','secret.pdf'),('other','okay');
      set request.jwt.claim.role='service_role'; set role service_role;
    `);

 await db.exec('reset role');
 await db.exec(await readFile(new URL('../../supabase/migrations/20260925182949_candidate_ai_interviews.sql',import.meta.url),'utf8'));
 await db.exec(`alter table jobs add column description text; update jobs set description='TypeScript PostgreSQL APIs testing leadership';set role service_role`);
 const rpc=async(fn,args=[])=>(await db.query(`select public.${fn}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as result`,args)).rows[0].result;
 const payload={submission_id:uid(880),job_id:1,first_name:'Synthetic',last_name:'Test',email:'synthetic@example.test',questionnaire:{experience:'Five years'}};
 await db.query("insert into application_uploads(path) values('synthetic/resume.pdf')");
 await rpc('ats_submit',[payload,'hash','synthetic/resume.pdf','resume.pdf']);
 const {id}= (await db.query('select id from applications where submission_id=$1',[uid(880)])).rows[0];
 assert.equal((await db.query("select count(*)::int n from application_outbox where event_key=$1",['ack:'+id])).rows[0].n,1);
 await rpc('ats_submit',[payload,'hash','synthetic/resume.pdf','resume.pdf']);
 assert.equal((await db.query('select count(*)::int n from application_ai_reviews')).rows[0].n,1,'submission retry does not duplicate assessment');
 assert.equal((await db.query("select count(*)::int n from application_outbox where kind='acknowledgment'")).rows[0].n,1,'one thank-you email');
 await assert.rejects(rpc('ats_interview_admin',[uid(2),id,'detail']),/forbidden/);
 const claims=(await db.query('select * from ats_claim_assessments()')).rows;
 assert.equal(claims.length,1);assert.equal((await db.query('select * from ats_claim_assessments()')).rows.length,0);
 const rubric={criteria:Array.from({length:5},(_,i)=>({requirement:'Criterion '+i,job_quote:'TypeScript'})),questions:Array.from({length:8},(_,i)=>'Question '+i)};
 await db.query("update application_ai_reviews set state='review',score=8,assessment=$1,rubric=$2 where application_id=$3",[{items:[]},rubric,id]);
 await assert.rejects(rpc('ats_interview_admin',[uid(2),id,'approve','Human reviewed evidence and questions','a'.repeat(64),'https://aliviosearchpartners.com/client/interview#'+'b'.repeat(64)]),/forbidden/);
 await assert.rejects(rpc('ats_interview_admin',[uid(4),id,'approve','short','a'.repeat(64),'https://aliviosearchpartners.com/client/interview#'+'b'.repeat(64)]),/invalid_approval/);
 await rpc('ats_interview_admin',[uid(4),id,'approve','Human reviewed evidence and role questions','a'.repeat(64),'https://aliviosearchpartners.com/client/interview#'+'b'.repeat(64)]);
 await rpc('ats_interview_admin',[uid(4),id,'approve','Human reviewed evidence and role questions','c'.repeat(64),'https://aliviosearchpartners.com/client/interview#'+'d'.repeat(64)]);
 assert.equal((await db.query("select count(*)::int n from application_outbox where event_key=$1",['ai-interview:'+id])).rows[0].n,1,'one invitation');
 const detail=await rpc('ats_interview_admin',[uid(4),id,'detail']);assert.equal(detail.review.token_hash,undefined);
 await assert.rejects(rpc('ats_interview_session',['wrong','info']),/invalid_interview_link/);
 const before=await rpc('ats_interview_session',['a'.repeat(64),'info']);assert.deepEqual(before.questions,[]);
 await assert.rejects(rpc('ats_interview_session',['a'.repeat(64),'upload',0,'video/webm']),/invalid_interview_session/);
 const start=await rpc('ats_interview_session',['a'.repeat(64),'start']);
 assert.equal(Date.parse(start.deadline)-Date.parse(start.server_now),1800000);
 const resumed=await rpc('ats_interview_session',['a'.repeat(64),'start']);assert.equal(start.deadline,resumed.deadline);
 await assert.rejects(rpc('ats_interview_session',['a'.repeat(64),'upload',2,'video/webm']),/invalid_question_order/);
 const answer=await rpc('ats_interview_session',['a'.repeat(64),'upload',0,'video/webm']);
 assert.equal((await rpc('ats_interview_session',['a'.repeat(64),'upload',0,'video/webm'])).path,answer.path);
 await rpc('ats_interview_session',['a'.repeat(64),'confirm',0]);
 await assert.rejects(rpc('ats_interview_session',['a'.repeat(64),'finish']),/invalid_incomplete_interview/);
 await db.query("update application_ai_reviews set started_at=now()-interval '31 minutes',deadline=now()-interval '1 minute' where application_id=$1",[id]);
 assert.equal((await rpc('ats_interview_session',['a'.repeat(64),'info'])).state,'expired');
 await assert.rejects(rpc('ats_interview_session',['a'.repeat(64),'upload',1,'video/webm']),/invalid_interview_session/);
 assert.equal((await rpc('ats_interview_session',['a'.repeat(64),'human'])).state,'human_requested');
 const message=(await db.query("select id from application_outbox where event_key=$1",['ai-interview:'+id])).rows[0];
 await db.query("update application_outbox set status='sending',lease_token=$1,lease_until=now()+interval '5 minutes' where id=$2",[uid(900),message.id]);
 assert.equal(await rpc('ats_prepare_message',[message.id,uid(900),'test@example.test','internal@example.test','',false]),null,'human alternative cancels unsent AI invitation');
 assert.equal((await db.query('select status from application_outbox where id=$1',[message.id])).rows[0].status,'cancelled');
 await db.query("update applications set messages_stopped=true where id=$1",[id]);
 await assert.rejects(rpc('ats_interview_session',['a'.repeat(64),'info']),/invalid_interview_link/);
 await db.exec('reset role;set role authenticated');
 await assert.rejects(db.query('select * from application_ai_reviews'),/permission denied/);
 await assert.rejects(rpc('ats_interview_session',['a'.repeat(64),'start']),/permission denied/);
 await db.exec('reset role');
 await db.query("insert into storage.objects(bucket_id,name) values('application-interviews','private.webm')");
 await db.exec('set role authenticated');
 assert.equal((await db.query("select * from storage.objects where bucket_id='application-interviews'")).rows.length,0);
 await db.exec('reset role;set role service_role');
 await db.query('delete from applications where id=$1',[id]);
 assert.equal((await db.query('select path from application_interview_cleanup')).rows[0].path,answer.path);
 }finally{await db.close();}
});
